@extends('layouts.admin')

@section('title', 'SmartKasir - Admin Panel')

@section('content')
    @if(empty($page))
        @include('admin.home')
    @elseif($page === 'barang')
        @include('admin.barang')
    @elseif($page === 'barang/details')
        @include('admin.barang_details')
    @elseif($page === 'barang/edit')
        @include('admin.barang_edit')
    @elseif($page === 'kategori')
        @include('admin.kategori')
    @elseif($page === 'jual')
        @include('admin.jual')
    @elseif($page === 'laporan')
        @include('admin.laporan')
    @elseif($page === 'kasir')
        @include('admin.kasir')
    @elseif($page === 'kasir/details')
        @include('admin.kasir_details')
    @elseif($page === 'kasir/edit')
        @include('admin.kasir_edit')
    @elseif($page === 'pengaturan')
        @include('admin.pengaturan')
    @elseif($page === 'pesan')
        @include('admin.pesan')
    @elseif($page === 'user')
        @include('admin.user')
    @endif
@endsection
